import {loadTMLibraries} from './tm-loader.js';
const $=selector=>document.querySelector(selector);
const video=$('#waste-camera'),canvas=$('#waste-capture');
let stream,modelPromise,photo=null,predictions=[],report=null,busy=false,history=[],revision=0;
const tabs=[...document.querySelectorAll('[data-tm-step]')];
function step(index){tabs.forEach((tab,i)=>{const active=i===index;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;const panel=$(`#tm-panel-${i}`);panel.classList.toggle('is-active',active);panel.setAttribute('aria-hidden',String(!active));panel.inert=!active})}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>step(i));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;step(j);tabs[j].focus()})});
function status(text){$('#waste-status').textContent=text}
function setBusy(value){busy=value;$('#waste-snapshot').disabled=value||!stream;$('#waste-analyse').disabled=value||!photo;$('#waste-send').disabled=value;$('#waste-upload').disabled=value;$('#waste-upload-trigger').disabled=value;$('#waste-camera-toggle').disabled=value}
function stopCamera(){stream?.getTracks().forEach(track=>track.stop());stream=null;video.srcObject=null;video.hidden=true;canvas.hidden=!photo;$('#waste-empty').hidden=!!photo;$('#waste-camera-toggle').textContent='Enable camera';$('#waste-snapshot').disabled=true}
$('#waste-camera-toggle').addEventListener('click',async()=>{
  if(stream){stopCamera();status('Camera stopped. Your selected photo is still available.');return}
  if(!navigator.mediaDevices?.getUserMedia){status('Camera requires HTTPS or localhost. You can upload a photo instead.');return}
  setBusy(true);
  try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280},height:{ideal:960}},audio:false});video.srcObject=stream;await video.play();video.hidden=false;canvas.hidden=true;$('#waste-empty').hidden=true;$('#waste-camera-toggle').textContent='Stop camera';$('#waste-input-mode').textContent='LIVE CAMERA';status('Frame one item, then capture. The full frame is analysed.');document.dispatchEvent(new CustomEvent('autarkeia:waste-camera'))}
  catch{stopCamera();status('Camera could not start. Check permission or upload a photo.')}
  finally{setBusy(false)}
});
function newPhoto(source,width,height){
  revision++;report=null;predictions=[];history=[];$('#waste-messages').replaceChildren();$('#waste-bars').replaceChildren();$('#waste-timing').textContent='CLASSIFYING';$('#waste-provider').textContent='LOCAL MODEL';$('#waste-chat-provider').textContent='';
  const scale=Math.min(1,960/Math.max(width,height));canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height);photo=canvas.toDataURL('image/jpeg',.85);canvas.hidden=false;video.hidden=true;$('#waste-empty').hidden=true;$('#waste-input-mode').textContent='SELECTED PHOTO';
  const result=$('#waste-result');result.replaceChildren();const title=document.createElement('h3');title.id='waste-result-title';title.textContent='Reading your image…';result.append(title);
}
async function model(){if(!modelPromise)modelPromise=(async()=>{await loadTMLibraries();return window.tmImage.load('models/waste/model.json','models/waste/metadata.json')})().catch(e=>{modelPromise=null;throw e});return modelPromise}
function paragraph(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p)}
function renderLocal(){const result=$('#waste-result');result.replaceChildren();const eyebrow=document.createElement('span');eyebrow.className='waste-result-label';eyebrow.textContent='LOCAL PREDICTION · NOT YET REVIEWED BY AI';const title=document.createElement('h3');title.id='waste-result-title';title.textContent=predictions[0]?.className||'Local model unavailable';result.append(eyebrow,title);paragraph(result,predictions.length?`The model assigns ${(predictions[0].probability*100).toFixed(1)}% confidence to this class. Check the photo and class scores below.`:'You can retry with another image, or request an AI image review.');paragraph(result,'Select “Analyse with AI” for a separate visual review, possible chemical composition and practical handling advice.');}
function renderBars(){const bars=$('#waste-bars');bars.replaceChildren();for(const prediction of predictions){const row=document.createElement('div');row.className='waste-score';const label=document.createElement('div');label.className='waste-score-label';const name=document.createElement('span');name.textContent=prediction.className;const value=document.createElement('span');value.textContent=`${(prediction.probability*100).toFixed(1)}%`;label.append(name,value);const progress=document.createElement('progress');progress.max=1;progress.value=prediction.probability;progress.setAttribute('aria-label',`${prediction.className} confidence`);row.append(label,progress);bars.append(row)}}
async function classify(){setBusy(true);status('Loading the local model and classifying your photo…');try{const tm=await model();const start=performance.now();predictions=(await tm.predict(canvas)).sort((a,b)=>b.probability-a.probability);renderBars();$('#waste-timing').textContent=`${Math.round(performance.now()-start)} MS INFERENCE · ${predictions.length} CLASSES · THIS DEVICE`;status('Local prediction ready. AI review is available when you choose to share this photo.')}catch{status('Local model could not load. Check your connection and retry, or use AI image review.');$('#waste-timing').textContent='LOCAL MODEL UNAVAILABLE';paragraph($('#waste-bars'),'No confidence scores available.')}finally{renderLocal();setBusy(false)}}
$('#waste-snapshot').addEventListener('click',async()=>{if(!stream||video.readyState<2)return;newPhoto(video,video.videoWidth,video.videoHeight);stopCamera();await classify()});
$('#waste-upload-trigger').addEventListener('click',()=>$('#waste-upload').click());
$('#waste-upload').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>12*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){status('Choose a JPG, PNG or WebP image smaller than 12 MB.');return}setBusy(true);const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();stopCamera();newPhoto(img,img.naturalWidth,img.naturalHeight);await classify()}catch{status('This image could not be opened. Try a JPG or PNG photo.');setBusy(false)}finally{URL.revokeObjectURL(url)}});
async function api(payload){const response=await fetch('/api/waste',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(95000)});let data;try{data=await response.json()}catch{throw new Error('The AI service is not available on this static preview. Open the server-backed website.')}if(!response.ok)throw new Error(data.error||'The AI service is unavailable. Please try again.');return data}
function field(parent,title,value){if(!value)return;const section=document.createElement('div');section.className='waste-report-field';const h=document.createElement('h4');h.textContent=title;section.append(h);if(Array.isArray(value)){const list=document.createElement('ul');value.forEach(text=>{const item=document.createElement('li');item.textContent=String(text);list.append(item)});section.append(list)}else paragraph(section,String(value));parent.append(section)}
function renderReport(data){const root=$('#waste-result');root.replaceChildren();const eyebrow=document.createElement('span');eyebrow.className='waste-result-label';eyebrow.textContent='AI IMAGE REVIEW';const h=document.createElement('h3');h.id='waste-result-title';h.textContent=data.identification;root.append(eyebrow,h);field(root,'Evidence & uncertainty',data.evidence);field(root,'Possible material',data.material);field(root,'Chemical composition & structure',data.chemistry);field(root,'Environmental impact',data.impact);field(root,'Practical next steps',data.steps);field(root,'Reuse & potential value',data.reuse);field(root,'Check before acting',data.caution)}
$('#waste-analyse').addEventListener('click',async()=>{if(!photo||busy)return;setBusy(true);const selected=revision;$('#waste-provider').textContent='REVIEWING IMAGE';status('AI is reviewing your selected photo and local class scores…');try{const data=await api({action:'analyse',image:photo,predictions});if(selected!==revision)return;report=data.report;renderReport(report);$('#waste-provider').textContent=data.provider;$('#waste-chat-provider').textContent=data.provider;status(`Review ready from ${data.provider}${data.fallback?' · backup provider used':''}. You can ask a follow-up below.`)}catch(e){$('#waste-provider').textContent='AI UNAVAILABLE';status(e.name==='TimeoutError'?'AI review timed out. Please retry.':e.message)}finally{setBusy(false)}});
function message(role,text,provider){const node=document.createElement('div');node.className=`waste-message ${role}`;const label=document.createElement('span');label.textContent=role==='user'?'YOU':provider||'ASSISTANT';node.append(label,document.createTextNode(text));$('#waste-messages').append(node);node.scrollIntoView({block:'nearest',behavior:'smooth'});return node}
$('.waste-prompts').addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){$('#waste-question').value=e.target.dataset.question;$('#waste-question').focus()}});
$('#waste-chat-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const question=$('#waste-question').value.trim();if(!question)return;setBusy(true);message('user',question);$('#waste-question').value='';$('#waste-chat-status').textContent='Thinking about your question…';try{const data=await api({action:'chat',image:photo,predictions,report,history:history.slice(-8),question});message('assistant',data.answer,data.provider);history.push({role:'user',content:question},{role:'assistant',content:data.answer});$('#waste-chat-provider').textContent=data.provider;$('#waste-chat-status').textContent=data.fallback?'Answered by the backup provider.':''}catch(e){$('#waste-chat-status').textContent=e.name==='TimeoutError'?'The reply timed out. Please retry.':e.message;$('#waste-question').value=question}finally{setBusy(false)}});
document.addEventListener('autarkeia:scene',e=>{if(e.detail.id!=='waste-lab')stopCamera();if(e.detail.id!=='waste-intro')$('#tm-preview-video').pause()});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera();$('#tm-preview-video').pause()}});
addEventListener('pagehide',stopCamera);
