const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const forms={closed:['Condensation','Close your hand to gather the particles.'],open:['Expansion','Open your hand to spread the particles.'],one:['Orbit','Raise one finger to form a ring.'],two:['Double helix','Raise two fingers to form a helix.'],three:['Waveform','Raise three fingers to form a wave.'],check:['Ignition','Extend your thumb and index finger for fire.']};
const keys=Object.keys(forms);let gesture='open',depth=1,scale=1,rotation=.3,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,stream=null,active=false,runId=0,lastFrame=-1,handWorker=null,workerPending=false,handReady=null,workerReady=false,models={},lastPrediction=0,candidate='',candidateCount=0;
const mappings={image:{'Class 1':'closed','Class 2':'open','Class 3':'one','Class 4':'two','Class 5':'three','Class 6':'check'},pose:{'Class 1':'closed','Class 2':'closed','Class 3':'open','Class 4':'open','Class 5':'one','Class 6':'two','Class 7':'three','Class 8':'check'}};
function setForm(key,manual=false){if(!forms[key])return;gesture=key;$$('[data-gesture]').forEach(b=>{const on=b.dataset.gesture===key;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});$('#shape-number').textContent=`FORM / 0${keys.indexOf(key)+1}`;$('#shape-name').textContent=forms[key][0];$('#shape-description').textContent=forms[key][1];if(manual){$('#detected').textContent='Manual exploration';$('#mode-label').textContent=active?'CAMERA ON · MANUAL PREVIEW':'EXPLORATION MODE'}drawMatter(performance.now());}
$$('[data-gesture]').forEach(b=>b.addEventListener('click',()=>setForm(b.dataset.gesture,true)));
function setDepth(value){depth=Math.max(.45,Math.min(2.2,Number(value)));$('#depth').value=depth;$('#depth-value').value=depth.toFixed(2)+'×';if(paused){scale=depth;drawMatter(0)}}
$('#depth').addEventListener('input',e=>setDepth(e.target.value));$('#reset').onclick=()=>{rotation=.3;setDepth(1);setForm('open',true)};
// Navbar hide/show is managed by scenes.js in scene-mode.
const motionBtn=$('#motion');if(motionBtn)motionBtn.onclick=()=>{paused=!paused;syncMotion()};function syncMotion(){document.body.classList.toggle("motion-paused",paused);if(motionBtn){motionBtn.textContent=paused?'▶ Resume motion':'Ⅱ Pause motion';motionBtn.setAttribute('aria-pressed',paused)}}syncMotion();
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.lab').requestFullscreen()}catch{status('Fullscreen is unavailable in this browser.')}};
function fit(canvas){const rect=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.6);if(canvas.width!==Math.round(rect.width*d)||canvas.height!==Math.round(rect.height*d)){canvas.width=Math.round(rect.width*d);canvas.height=Math.round(rect.height*d)}return {w:rect.width,h:rect.height,d}}
const universe=$('#universe'),uc=universe.getContext('2d'),aurora=$('#aurora'),ac=aurora?aurora.getContext('2d'):null,matter=$('#matter'),mc=matter.getContext('2d');
function drawAurora(ms){if(!ac)return;const {w,h,d}=fit(aurora);ac.setTransform(d,0,0,d,0,0);ac.clearRect(0,0,w,h);const t=ms*.00018;for(let i=0;i<4;i++){const cx=w*(.15+i*.22+Math.sin(t+i*1.3)*.07),cy=h*(.08+Math.cos(t*.7+i*.9)*.04),ry=h*(.12+Math.sin(t*.5+i)*.04),rx=w*(.28+i*.04);const g=ac.createRadialGradient(cx,cy+ry*.4,0,cx,cy,ry*1.6);const colors=[['#7359b820','#5a3f9810','#3d2d7205'],['#2e6e8a18','#1d5f7a10','#0d3d5004'],['#9b5e3a14','#7a4a2e0e','#4d2e1a04'],['#4a5e9218','#3a4e8010','#1e2d5004']];const [c1,c2,c3]=colors[i%4];g.addColorStop(0,c1);g.addColorStop(.5,c2);g.addColorStop(1,c3);ac.fillStyle=g;ac.beginPath();ac.ellipse(cx,cy,rx,ry,Math.sin(t*.3+i)*.3,0,Math.PI*2);ac.fill()}}
let seed=731;function rnd(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
const stars=Array.from({length:145},()=>[rnd(),rnd(),rnd()]);const particles=Array.from({length:1250},(_,i)=>({u:rnd(),v:rnd(),r:rnd(),i}));
function drawUniverse(ms){const {w,h,d}=fit(universe);uc.setTransform(d,0,0,d,0,0);uc.clearRect(0,0,w,h);const t=ms*.000055;for(const [x,y,r] of stars){uc.fillStyle=`rgba(202,191,223,${.12+r*.45})`;uc.beginPath();uc.arc(x*w,((y-t*.02+1)%1)*h,.4+r*.8,0,7);uc.fill()}const x=w*(w<650?.83:.76)+Math.sin(t)*w*.025,y=h*(w<650?.53:.46)+Math.cos(t*.8)*h*.025,r=Math.min(w*.23,h*.30);let glow=uc.createRadialGradient(x,y,r*.4,x,y,r*2);glow.addColorStop(0,'#74477d23');glow.addColorStop(.5,'#55384b17');glow.addColorStop(1,'#09090e00');uc.fillStyle=glow;uc.fillRect(0,0,w,h);uc.save();uc.translate(x,y);uc.rotate(-.38);for(let n=0;n<3;n++){uc.strokeStyle=['#bb90b22b','#c2948238','#8e83bb1b'][n];uc.lineWidth=n===1?1.5:.7;uc.beginPath();uc.ellipse(0,0,r*(1.55+n*.13),r*(.38+n*.09),0,0,Math.PI*2);uc.stroke()}for(let i=0;i<22;i++){const a=t*(.5+i%3*.2)+i*2.4;uc.fillStyle=i%3?'#897e9a88':'#d4b39aaa';uc.beginPath();uc.arc(Math.cos(a)*r*1.72,Math.sin(a)*r*.47,1+(i%3),0,7);uc.fill()}uc.restore();let planet=uc.createRadialGradient(x-r*.45,y-r*.5,0,x+r*.1,y+r*.15,r*1.2);planet.addColorStop(0,'#544453');planet.addColorStop(.3,'#292030');planet.addColorStop(.67,'#111019');planet.addColorStop(1,'#08090e');uc.fillStyle=planet;uc.beginPath();uc.arc(x,y,r,0,7);uc.fill();uc.strokeStyle='#9c769547';uc.lineWidth=1;uc.stroke();uc.save();uc.translate(x,y);uc.rotate(-.38);uc.strokeStyle='#c3988266';uc.beginPath();uc.ellipse(0,0,r*1.72,r*.47,0,0,Math.PI);uc.stroke();uc.restore();}
function point(p,t){const a=p.u*Math.PI*2,b=Math.acos(2*p.v-1);let x,y,z;switch(gesture){case'closed':case'open':{const r=(gesture==='closed'?.42:1.12)*(0.8+.2*p.r);x=Math.sin(b)*Math.cos(a)*r;y=Math.cos(b)*r;z=Math.sin(b)*Math.sin(a)*r;break}case'one':{const r=.85+.16*Math.cos(p.v*6.283);x=Math.cos(a)*r;y=Math.sin(p.v*6.283)*.16;z=Math.sin(a)*r;break}case'two':{const q=p.u*6.283*2+t*.4,side=p.i%2*Math.PI;x=Math.cos(q+side)*.55;y=(p.u-.5)*2.5;z=Math.sin(q+side)*.55;x+=(p.r-.5)*.1;break}case'three':{x=(p.u-.5)*2.5;z=(p.v-.5)*1.6;y=Math.sin(x*4+t+z*3)*.33+(p.i%3-1)*.35;break}case'check':{const life=(p.u+t*.22)%1,width=(1-life)*.65;x=Math.cos(a*7+t*2)*width*p.r+Math.sin(life*7+t)*life*.16;y=.9-life*2.4;z=Math.sin(a*7+t)*width*p.r;break}}const angle=rotation+(paused?0:t*.12),c=Math.cos(angle),s=Math.sin(angle),xx=x*c-z*s,zz=x*s+z*c;return [xx,y*.94-zz*.2,y*.2+zz*.94]}
function drawMatter(ms){const {w,h,d}=fit(matter);mc.setTransform(d,0,0,d,0,0);mc.clearRect(0,0,w,h);scale+=(depth-scale)*.07;const t=paused?0:ms*.001,unit=Math.min(w*.29,h*.30)*scale;mc.strokeStyle='#70637c18';mc.lineWidth=.6;mc.beginPath();mc.moveTo(w*.12,h*.5);mc.lineTo(w*.88,h*.5);mc.moveTo(w*.5,h*.12);mc.lineTo(w*.5,h*.88);mc.stroke();for(const p of particles){const target=point(p,t);if(!p.position||paused)p.position=target;p.position=p.position.map((v,i)=>v+(target[i]-v)*.12);const [x,y,z]=p.position,perspective=3.5/(3.5-z*.35),px=w/2+x*unit*perspective,py=h*.47+y*unit*perspective,alpha=.25+(.5+z*.2)*.55;mc.fillStyle=gesture==='check'?`hsla(${18+48*(1-(p.u+t*.22)%1)},100%,${55+p.r*30}%,${alpha})`:`hsla(${p.i%5===0?30:263},${p.i%5===0?55:34}%,${65+p.r*25}%,${alpha})`;mc.beginPath();mc.arc(px,py,(gesture==='check'?1.4:1)*(.5+p.r)*perspective,0,7);mc.fill()}}
let dragging=false,prevX=0;matter.addEventListener('pointerdown',e=>{dragging=true;prevX=e.clientX;matter.setPointerCapture(e.pointerId)});matter.addEventListener('pointermove',e=>{if(dragging){rotation+=(e.clientX-prevX)*.009;prevX=e.clientX;drawMatter(performance.now())}const r=matter.getBoundingClientRect();$('#coord-x').textContent=((e.clientX-r.left)/r.width).toFixed(2);$('#coord-y').textContent=((e.clientY-r.top)/r.height).toFixed(2)});matter.addEventListener('pointerup',()=>dragging=false);matter.addEventListener('pointercancel',()=>dragging=false);matter.tabIndex=0;matter.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')rotation-=.1;else if(e.key==='ArrowRight')rotation+=.1;else if(e.key==='ArrowUp')setDepth(depth+.1);else if(e.key==='ArrowDown')setDepth(depth-.1);else return;e.preventDefault();drawMatter(performance.now())});
let prevTime=0,animationTime=0;function animate(ms){if(ms-prevTime>32){const dt=prevTime?Math.min(ms-prevTime,70):0;prevTime=ms;if(!document.hidden&&!paused){animationTime+=dt;drawUniverse(animationTime);drawAurora(animationTime);const r=matter.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)drawMatter(animationTime)}}requestAnimationFrame(animate)}requestAnimationFrame(animate);addEventListener('resize',()=>{drawUniverse(animationTime);drawAurora(animationTime);drawMatter(animationTime)});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{paused=e.matches;syncMotion()});drawUniverse(0);drawAurora(0);setForm('open');
function status(s){$('#camera-status').textContent=s}function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{s.remove();reject(new Error('A detection library could not load. Check your connection and retry.'))};document.head.append(s)})}
let tmReady;async function loadTM(kind){if(models[kind])return models[kind];if(!tmReady)tmReady=(async()=>{await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.3.1/dist/tf.min.js');await loadScript('https://cdn.jsdelivr.net/npm/@teachablemachine/image@0.8.5/dist/teachablemachine-image.min.js');await loadScript('https://cdn.jsdelivr.net/npm/@teachablemachine/pose@0.8.6/dist/teachablemachine-pose.min.js')})().catch(e=>{tmReady=null;throw e});await tmReady;models[kind]=await(kind==='image'?window.tmImage:window.tmPose).load(`models/${kind}/model.json`,`models/${kind}/metadata.json`);return models[kind]}
function initHands(){if(handReady)return handReady;handReady=new Promise((resolve,reject)=>{handWorker=new Worker('hand-worker.js');const timeout=setTimeout(()=>fail('Hand tracking timed out. Check your connection and retry.'),60000);function fail(message){clearTimeout(timeout);handWorker?.terminate();handWorker=null;handReady=null;workerReady=false;workerPending=false;reject(new Error(message));if(active&&$('#engine').value==='hands'){stopCamera();status(message)}}handWorker.onmessage=({data})=>{if(data.type==='ready'){clearTimeout(timeout);workerReady=true;resolve()}else if(data.type==='error')fail(data.message);else if(data.type==='result'){workerPending=false;if(active)handleHand(data.result)}};handWorker.onerror=()=>fail('Hand tracking could not load. Try another detection source.')});return handReady}
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);function inferHand(l){const palm=distance(l[0],l[9]),fingers=[8,12,16,20].map(i=>distance(l[i],l[0])>distance(l[i-2],l[0])*1.18&&distance(l[i],l[i-3])>palm*.45),thumb=distance(l[4],l[17])>distance(l[3],l[17])*1.15,count=fingers.filter(Boolean).length;if(count>=4)return'open';if(count===1&&fingers[0]&&thumb)return'check';if(count===0)return'closed';if(count===1&&fingers[0])return'one';if(count===2)return'two';if(count===3)return'three';return null}
function stabilize(key){if(!key){candidate='';candidateCount=0;return}if(candidate===key)candidateCount++;else{candidate=key;candidateCount=1}if(candidateCount>=3)setForm(key)}
function handleHand(result){const l=result.landmarks?.[0],overlay=$('#landmarks'),ctx=overlay.getContext('2d');overlay.width=640;overlay.height=480;ctx.clearRect(0,0,640,480);if(!l){if($('#engine').value==='hands'){$('#detected').textContent='No hand in view';status('Show one hand, with your wrist and fingertips visible.')}return}const size=Math.hypot((l[0].x-l[9].x)*640/480,l[0].y-l[9].y),target=Math.max(.45,Math.min(2.2,size/.19));setDepth(depth+(target-depth)*.18);for(const chain of [[0,1,2,3,4],[0,5,6,7,8],[5,9,10,11,12],[9,13,14,15,16],[13,17,18,19,20],[0,17]]){ctx.beginPath();chain.forEach((n,i)=>i?ctx.lineTo(l[n].x*640,l[n].y*480):ctx.moveTo(l[n].x*640,l[n].y*480));ctx.strokeStyle='#e6bea0';ctx.lineWidth=2;ctx.stroke()}for(const p of l){ctx.beginPath();ctx.arc(p.x*640,p.y*480,3,0,7);ctx.fillStyle='#d3bbff';ctx.fill()}if($('#engine').value==='hands'){const key=inferHand(l);stabilize(key);$('#detected').textContent=key?`${forms[key][0]} · Hand landmarks`:'Gesture unclear';$('#mode-label').textContent='LIVE · HAND TRACKING';status('Tracking your hand. Move closer or further away.')}}
function stopCamera(){active=false;runId++;stream?.getTracks().forEach(t=>t.stop());stream=null;$('#camera').srcObject=null;$('#camera-placeholder').style.display='flex';$('#camera-toggle').innerHTML='Enable camera <span>↗</span>';$('#mode-label').textContent='EXPLORATION MODE';$('#detected').textContent='Manual exploration';$('#predictions').replaceChildren();const c=$('#landmarks');c.getContext('2d').clearRect(0,0,c.width,c.height);status('Camera off. Explore with the controls below.');candidateCount=0;lastFrame=-1}
$('#camera-toggle').onclick=async()=>{if(active){stopCamera();return}const token=++runId;$('#camera-toggle').disabled=true;$('#engine').disabled=true;status('Preparing detection. The first load may take a moment…');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access needs HTTPS or localhost in a supported browser.');const engine=$('#engine').value;await(engine==='hands'?initHands():loadTM(engine));if(token!==runId)return;stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:640},height:{ideal:480},facingMode:'user'},audio:false});if(token!==runId){stream.getTracks().forEach(t=>t.stop());stream=null;return}const video=$('#camera');video.srcObject=stream;await video.play();active=true;$('#camera-placeholder').style.display='none';$('#camera-toggle').innerHTML='Stop camera <span>×</span>';status('Camera connected. Place your hand in the frame.');$('#mode-label').textContent='LIVE · '+(engine==='hands'?'HAND TRACKING':engine.toUpperCase()+' MODEL');if(engine!=='hands')initHands().catch(()=>{if(active)status('Model active. Hand depth unavailable; use the depth slider.')});stream.getVideoTracks()[0].addEventListener('ended',()=>{if(active){stopCamera();status('The camera disconnected. Connect it again to continue.')}});inferenceLoop(token)}catch(e){stopCamera();status(e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your browser, then retry.':e.name==='NotFoundError'?'No camera found. Connect a camera or use manual exploration.':e.message||'Camera could not start. Please retry.')}finally{$('#camera-toggle').disabled=false;$('#engine').disabled=false}};
async function inferenceLoop(token){if(!active||token!==runId)return;try{const video=$('#camera'),now=performance.now(),kind=$('#engine').value;if(!document.hidden&&video.readyState>=2&&video.currentTime!==lastFrame){lastFrame=video.currentTime;if(handWorker&&workerReady&&!workerPending){workerPending=true;const bitmap=await createImageBitmap(video);if(active&&token===runId)handWorker.postMessage({type:'frame',bitmap,time:now},[bitmap]);else{bitmap.close();workerPending=false}}if(kind!=='hands'&&now-lastPrediction>160){lastPrediction=now;const model=models[kind];let predictions;if(kind==='image')predictions=await model.predict(video);else{const {posenetOutput}=await model.estimatePose(video);predictions=await model.predict(posenetOutput)}if(!active||token!==runId)return;renderPredictions(predictions);const top=[...predictions].sort((a,b)=>b.probability-a.probability)[0],key=top.probability>=.72?mappings[kind][top.className]:null;stabilize(key);$('#detected').textContent=`${top.className} · ${Math.round(top.probability*100)}%${key?' · '+forms[key][0]:''}`;status(key?'Model connected. Gesture predictions are live.':'Uncertain prediction. Improve lighting or adjust your pose.');$('#mode-label').textContent='LIVE · '+kind.toUpperCase()+' MODEL'}}}catch(e){stopCamera();status('Detection stopped: '+(e.message||'Please retry.'));return}if(active&&token===runId)setTimeout(()=>inferenceLoop(token),70)}
function renderPredictions(predictions){$('#predictions').replaceChildren(...[...predictions].sort((a,b)=>b.probability-a.probability).slice(0,3).map(p=>{const row=document.createElement('div');row.className='prediction';const label=document.createElement('span');label.textContent=p.className;const value=document.createElement('span');value.textContent=Math.round(p.probability*100)+'%';const bar=document.createElement('progress');bar.max=1;bar.value=p.probability;bar.setAttribute('aria-label',p.className+' confidence');row.append(label,value,bar);return row}))}
function renderMapping(){const kind=$('#engine').value;$('#mapping-details').hidden=kind==='hands';$('#mapping').replaceChildren();if(kind==='hands')return;Object.entries(mappings[kind]).forEach(([label,key])=>{const wrapper=document.createElement('label');wrapper.textContent=label;const s=document.createElement('select');s.setAttribute('aria-label',label+' gesture');for(const k of keys){const opt=document.createElement('option');opt.value=k;opt.textContent=forms[k][0];s.append(opt)}s.value=key;s.onchange=()=>mappings[kind][label]=s.value;wrapper.append(s);$('#mapping').append(wrapper)})}
$('#engine').onchange=()=>{stopCamera();renderMapping()};addEventListener('pagehide',()=>{stopCamera();handWorker?.terminate()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active){stopCamera();status('Camera paused because the page was hidden. Enable it to resume.')}});
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort());try{Promise.resolve(context.registerTool({name:'configure_interaction_field',description:'Set the manual particle form and depth without enabling the camera.',inputSchema:{type:'object',properties:{gesture:{type:'string',enum:keys},depth:{type:'number',minimum:.45,maximum:2.2}},required:['gesture','depth'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!forms[input.gesture]||typeof input.depth!=='number'||!Number.isFinite(input.depth)||input.depth<.45||input.depth>2.2)throw new Error('Invalid gesture or depth');stopCamera();setForm(input.gesture,true);setDepth(input.depth);return {gesture,depth}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}



